config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :carts, only: [:create, :new, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :edit, :update]
  resources :products
  devise_for :users, path: "/" ,path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "sessions"}
  
  namespace :admin do
    resources :orders, only: [:index, :edit, :update]
    resources :products
    
    root "static_pages#dashboard"
  end

    # get "/login", to: "sessions#new"
    # post "/login", to: "sessions#create"
    # delete "/logout", to: "sessions#destroy"
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :defaul_status

  belongs_to :user
  has_many :order_details, dependent: :destroy

  scope :sort_desc, ->{order(created_at: :desc)}
  scope :approved, ->{where(status: 1)}
  scope :orders, ->(user_id){where(user_id: user_id)}

  enum status: {pending: 0, approved: 1, cancel: 2, rejected: 3}

  def reject_order
    rejected!
    refund_quatity
  end

  def approve_order
    approved!
  end

  def cancel_order
    cancel!
    refund_quatity
  end

  def refund_quatity
    order_details.each do |d|
      d.product.update!(quatity: d.product[:quatity] + d[:quatity])
    end
  end

  private

  def defaul_status
    self.status = 0 if status.nil?
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :load_order, only: [:edit, :update]

  def index
    @orders = Order.page(params[:page]).per(Settings.per_page).sort_desc
    @result = load_data_to_view @orders
  end

  def edit
    @total = @order.order_details.reduce(0){|a, e| a + e[:price] * e[:quatity]}
  end

  def update
    ActiveRecord::Base.transaction do
      if params[:status].to_i == Order.statuses[:approved]
        @order.approve_order
      elsif params[:status].to_i == Order.statuses[:rejected]
        @order.reject_order
      end
      update_success
    end
  rescue StandardError
    flash[:error] = t "common.flash.order_fail"
    redirect_to admin_orders_path
  end

  private

  def load_data_to_view orders
    orders = orders.select(:id, :created_at, :status, :fullname, :phone_number)
    orders.includes(:order_details).map do |order|
      quatity = 0
      price = 0
      order.order_details.each do |d|
        quatity += d.quatity
        price += quatity * d.price
      end
      {
        order_quatity: quatity,
        price: price,
        status: order[:status],
        order_time: order[:created_at],
        order_id: order[:id],
        fullname: order[:fullname],
        phone_number: order[:phone_number]
      }
    end
  end

  def update_success
    message = t("common.flash.#{params[:status] == '1' ? 'approve' : 'reject'}")
    flash[:success] = message
    redirect_to admin_orders_path
  end

  def load_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:error] = t "common.flash.load_order_fail"
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin?
  before_action :load_order, only: [:edit, :update]

  def new
    @carts = summary_cart
    @sumary = @carts[-1]
    @carts.pop
  end

  def create
    ActiveRecord::Base.transaction do
      @order = current_user.orders.build(order_params)
      @order.save!
      create_order_detail @order[:id]
      flash[:success] = t "common.flash.order_success"
      session[:cart] = nil
      redirect_to root_path
    end
  rescue StandardError
    flash[:error] = t "common.flash.order_fail"
    redirect_to new_order_path
  end

  def update
    ActiveRecord::Base.transaction do
      @order.cancel_order
      flash[:success] = t "common.flash.cancel"
      redirect_to orders_path
    end
  rescue StandardError
    flash[:error] = t "common.flash.cancel_fail"
    redirect_to orders_path
  end

  def index
    @orders = Order.page(params[:page]).per(Settings.per_page)
                   .orders(current_user[:id]).sort_desc
    @result = load_data_to_view @orders
  end

  def edit
    @total = @order.order_details.reduce(0){|a, e| a + e[:price] * e[:quatity]}
  end

  private

  def load_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:error] = t "common.flash.load_order_fail"
    redirect_to orders_path
  end

  def load_data_to_view orders
    orders = orders.select(:id, :created_at, :status, :fullname, :phone_number)
    orders.includes(:order_details).map do |order|
      quatity = 0
      price = 0
      order.order_details.each do |d|
        quatity += d.quatity
        price += quatity * d.price
      end
      {
        order_quatity: quatity,
        price: price,
        status: order[:status],
        order_time: order[:created_at],
        order_id: order[:id],
        fullname: order[:fullname],
        phone_number: order[:phone_number]
      }
    end
  end

  def create_order_detail order_id
    session[:cart].each do |x, y|
      product = Product.find_by(id: x)
      if product.nil?
        session[:cart].delete(x)
        next
      end
      product[:quatity] = product[:quatity] - y
      product.save!
      price = product[:price]
      new_detail = OrderDetail.new(detail_params(order_id, x, y, price))
      new_detail.save!
    end
  end

  def order_params
    params.require(:order).permit(:fullname, :phone_number, :address)
  end

  def detail_params order_id, product_id, quatity, price
    {
      order_id: order_id,
      product_id: product_id,
      quatity: quatity,
      price: price
    }
  end

end

app/views/admin/orders/edit.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="wrapper-order">
    <div class="header">
      <div class="info-user">
        <p class="title" style="text-transform: uppercase;"><%= t ".title_card_address" %></p>
        <div class="card">
          <h3><%= @order[:fullname] %></h3>
          <p class="address"><%= t ".title_address" %><%= @order[:address] %></p>
          <p class="phone"><%= t ".title_phone" %><%= @order[:phone_number] %></p>
        </div>
      </div>
      <div class="delivery">
        <p class="title" style="text-transform: uppercase;"><%= t ".title_delivery" %></p>
        <div class="card">
          <%= t ".title_ship" %> <%= number_to_currency(0) %>
        </div>
      </div>
      <div class="payment">
        <p class="title" style="text-transform: uppercase;"><%= t ".title_payment_method" %></p>
        <div class="card">
          Cash on Delivery
        </div>
      </div>
    </div>
    <div class="wishlist-page">
      <div class="wishlist-page-inner">
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsive">
              <table class="table table-bordered">
                <thead class="thead-dark">
                  <tr>
                    <th><%= t ".title_product" %></th>
                    <th><%= t ".title_price" %></th>
                    <th><%= t ".title_quantity" %></th>
                    <th><%= t ".title_total" %></th>
                  </tr>
                </thead>
                <tbody class="align-middle">
                  <% @order.order_details.each do |item| %>
                    <tr>
                      <td>
                        <div class="img">
                          <%= image_tag "product-6.jpg" %>
                          <p><%= item.product[:name] %></p>
                        </div>
                      </td>
                      <td><%= number_to_currency(item[:price]) %></td>
                      <td>
                        <%= item[:quatity] %>
                      </td>
                      <td><%= number_to_currency(item[:quatity] * item[:price] ) %></td>
                    </tr>
                  <% end %>
                  
                  <tr>
                    <td style="border-right: none"></td>
                    <td style="border-right: none; border-left: none"></td>
                    <td style="border-right: none; text-align: end; border-left: none">
                      <div><strong><%= t ".sub_total" %></strong></div>
                      <div><strong><%= t ".ship" %></strong></div>
                      <div><strong><%= t ".total" %></strong></div>
                    </td>
                    <td style="border-left:none; text-align: end">
                      <div><%= number_to_currency(@total) %></div>
                      <div><%= number_to_currency(0) %></div>
                      <div><%= number_to_currency(@total) %></div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="action-order">
      <% unless @order.approved? || @order.rejected? %>
        <%= form_for :order, url: admin_order_path, method: :patch, html: {class: "form-inline"} do |f| %>
          <%= hidden_field_tag :status, 1 %>
          <%= button_tag(class: "btn btn-approve") do %>
            <%= t ".btn_approve" %>
          <% end %>
        <% end %>
      <% end %>
      
      <% unless @order.rejected? %>
        <%= form_for :order, url: admin_order_path, method: :patch, html: {class: "form-inline"} do |f| %>
          <%= hidden_field_tag :status, 3 %>
          <%= button_tag(class: "btn btn-reject", data: { confirm: t("common.flash.confirm_delete") }) do %>
            <%= t ".btn_reject" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/admin/orders/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="table-responsive">
    <table class="table table-striped table-sm table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th><%= t ".title_name" %></th>
          <th><%= t ".title_phone" %></th>
          <th><%= t ".title_time" %></th>
          <th><%= t ".title_quantity" %></th>
          <th><%= t ".title_total" %></th>
          <th><%= t ".title_status" %></th>
          <th><%= t ".title_action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @result.each_with_index  do |i, index| %>
          <tr id="table-item">
            <td><%= index + 1 %></td>
            <td><%= i[:fullname] %></td>
            <td><%= i[:phone_number] %></td>
            <td><%= i[:order_time].to_formatted_s(:long) %></td>
            <td><%= i[:order_quatity] %></td>
            <td><%= number_to_currency(i[:price]) %></td>
            <td>
              <%= label_tag i[:status], i[:status], class:"badge badge-#{i[:status] == 'rejected' || i[:status] == 'cancel' ? 'danger' : i[:status] == 'pending' ? 'primary' : 'success'}" %>
            </td>
            <td><%= link_to t(".btn_view_detail"), edit_admin_order_path(i[:order_id]), class: "btn btn-detail" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
</main>