config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :carts, only: [:create, :new, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :edit, :update]
  resources :products
  devise_for :users, path: "/" ,path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "sessions"}
  
  namespace :admin do
    resources :orders, only: [:index, :edit, :update]
    resources :products
    
    root "static_pages#dashboard"
  end

    # get "/login", to: "sessions#new"
    # post "/login", to: "sessions#create"
    # delete "/logout", to: "sessions#destroy"
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_admin?
  before_action :current_cart

  def create
    product_id = @current_cart[params[:product_id]].to_i
    if enough_quatity? params[:product_id], product_id + params[:quatity].to_i
      add_product_to_cart
    else
      flash[:error] = t "common.flash.quantity_invalid"
      redirect_to session[:forwarding_url] || root_path
    end
  end

  def update
    if @current_cart[params[:id]]
      new_total = @current_cart[params[:id]] + params[:cal].to_i
      change_total @current_cart, new_total
    end
    session[:cart] = @current_cart
    redirect_to new_cart_path
  end

  def new
    store_location
    @carts = summary_cart
    @sumary = @carts[-1]
    @carts.pop
  end

  def destroy
    @current_cart.delete(params[:id])
    session[:cart] = @current_cart
    redirect_to new_cart_path
  end

  private

  def add_product_to_cart
    is_have = change_quatity? unless @current_cart.empty?
    @current_cart[params[:product_id]] = params[:quatity].to_i unless is_have
    session[:cart] = @current_cart
    respond_to do |format|
      format.html{redirect_to root_path}
      format.js
    end
  end

  def change_total cart, total
    if enough_quatity?(params[:id], total)
      cart[params[:id]] = total
    else
      flash[:error] = t "common.flash.quantity_invalid"
    end
  end

  def change_quatity?
    return false unless @current_cart[params[:product_id]]

    @current_cart[params[:product_id]] += params[:quatity].to_i
  end

  def current_cart
    @current_cart = session[:cart] || Hash.new
  end

  def enough_quatity? product_id, quatity
    product = Product.find_by(id: product_id)
    quatity.positive? && quatity <= product[:quatity] if product
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart_number
    session[:cart]&.values&.inject(0, :+).to_i
  end

  def summary_cart
    carts = []
    sumary = 0
    session[:cart]&.each do |k, v|
      product = Product.find_by(id: k)
      unless product
        session[:cart].delete(k)
        next
      end

      total = v * product[:price]
      sumary += total
      cart = {
        name: product[:name],
        quatity: v,
        price: product[:price],
        total: total,
        id: product[:id],
        image: product.image
      }
      carts << cart
    end
    carts << sumary
  end
end

app/views/carts/create.js.erb

var current_text = $("#cart_number").text();
var counter = +$("#count").val()
var current_count= 0

if(counter){
  current_count = +current_text.substring(1,current_text.length - 1) + counter
}else {
  current_count = +current_text.substring(1,current_text.length - 1) + 1
}
$("#cart_number").html("(" + current_count + ")")

var message = $("#message_add_cart").val()
var type = $("#type_add_car").val()

var main = document.getElementById("custom-toast");
if (main) {
  var el = document.getElementById("trigger_show_toast")
  
  el.onclick = function() {
  var toast = document.createElement("div");

  toast.classList.add("custom-toast", `toast--success`);
  var toastId = setTimeout(() => {
    main.removeChild(toast);
  }, 2000 + 1000);
  toast.onclick = function (e) {
    if (e.target.closest(".toast__close")) {
      main.removeChild(toast);
      clearTimeout(toastId);
    }
  };
  var delay = (2000 / 1000).toFixed(2);
  toast.style.animation = `slideLeftIn ease 0.3s, fadeOut linear 1s ${delay}s forwards`
  toast.innerHTML = `
                <div class="toast__icon">
                <i class="far fa-check-circle"></i>
                </div>
                <div class="toast__body">
                <h3 class="toast__title">
                ${message}
                </h3>
                <p class="toast__msg">
                  ${type}
                </p>
                </div>
                <div class="toast__close">
                <i class="fas fa-times"></i>
                </div>
`;
  main.appendChild(toast);
  }
  el.click()
}

app/views/carts/new.html.erb
<!-- Cart Start -->
<div class="cart-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8">
        <div class="cart-page-inner">
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead class="thead-dark">
                <tr>
                  <th><%= t ".table.product" %></th>
                  <th><%= t ".table.price" %></th>
                  <th><%= t ".table.quantity" %></th>
                  <th><%= t ".table.total" %></th>
                  <th><%= t ".table.remove" %></th>
                </tr>
              </thead>
              <tbody class="align-middle">
                <% @carts.each do |c| %>
                  <tr>
                    <td>
                      <div class="img">
                        <%= image_tag c[:image], alt:"Product Image" if c[:image].attached? %>
                        <p><%= c[:name] %></p>
                      </div>
                    </td>
                    <td><%= number_to_currency(c[:price]) %></td>
                    <td>
                    
                        <div class="qty">
                          <%= form_for :carts, url: cart_path(c[:id]), method: :patch, html: {class: "form-inline"} do |f| %>
                            <%= hidden_field_tag :cal, -1 %>
                            <%= button_tag(class: "btn-minus") do %>
                              <i class="fa fa-minus"></i>
                            <% end %>
                          <% end %>
                          
                          <%= text_field_tag "", c[:quatity] %>
                          <%= form_for :carts, url: cart_path(c[:id]), method: :patch, html: {class: "form-inline"} do |f| %>
                            <%= hidden_field_tag :cal, 1 %>
                            <%= button_tag(class: "btn-plus") do %>
                              <i class="fa fa-plus"></i>
                            <% end %>
                          <% end %>
                        </div>
               
                    </td>
                    <td><%= number_to_currency(c[:total]) %></td>
                    <td>
                      <%= link_to cart_path(c[:id]), method: :delete do %>
                        <button><i class="fa fa-trash"></i></button>
                      <% end %>
                     
                    </td>
                  </tr>
                <% end %>
            
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="cart-page-inner">
          <div class="row">
            <div class="col-md-12">
              <div class="cart-summary">
                <div class="cart-content">
                  <h1><%= t ".summary.title" %></h1>
                  <p><%= t ".summary.sub_total" %><span> <%= number_to_currency(@sumary) %> </span></p>
                  <p><%= t ".summary.shipping" %><span><%= number_to_currency(0) %></span></p>
                  <h2><%= t ".summary.grand" %><span><%= number_to_currency(@sumary) %></span></h2>
                </div>
                <div class="cart-btn text-center mt-24">
                  <%= link_to t(".summary.btn_checkout"), new_order_path, class: "btn" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Cart End -->