config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :carts, only: [:create, :new, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :edit, :update]
  resources :products
  devise_for :users, path: "/" ,path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "sessions"}
  
  namespace :admin do
    resources :orders, only: [:index, :edit, :update]
    resources :products
    
    root "static_pages#dashboard"
  end

    # get "/login", to: "sessions#new"
    # post "/login", to: "sessions#create"
    # delete "/logout", to: "sessions#destroy"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :evaluates, dependent: :destroy

  has_one_attached :image

  validates :image, content_type: {
    in: ["image/jpeg", "image/gif", "image/png"],
    message: I18n.t("common.error_message.type_image")
  },
  size: {
    less_than: 5.megabytes,
    message: I18n.t("common.error_message.length_image")
  }
  validates :name, presence: true, uniqueness: true
  validates :quatity, presence: true, numericality: {greater_than: -1}
  validates :category_id, presence: true, exclusion: {in: Category.childrens}
  validates :price, presence: true, numericality: {greater_than: -1}
  validates :description, presence: true

  scope :sort_update, ->{order(updated_at: :desc)}
  scope :active, ->{where(deleted: 0)}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :load_category, only: [:create]
  before_action :load_product, only: [:edit, :update, :destroy]
  before_action :check_permission, only: [:edit, :update, :destroy]
  before_action :load_childrens, only: [:new, :create, :edit, :update]

  def index
    @products = Product.page(params[:page]).per(Settings.per_page)
                       .active.sort_update
  end

  def new
    @product = Product.new
  end

  def create
    @product = @category.products.build(product_params)
    if @product.save
      @product.image.attach(params[:product][:image])
      flash[:success] = t("common.flash.create_product_success")
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      image = params[:product][:image]
      @product.image.attach(image) unless image.nil?
      flash[:success] = t "common.flash.update_product_success"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    if @product.update(deleted: true)
      flash[:success] = t "common.flash.delete_product_success"
    else
      flash[:error] = t "common.flash.delete_product_fail"
    end
    redirect_to admin_products_path
  end

  private

  def check_permission
    authorize @product
  end

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product

    flash[:error] = t "common.flash.load_product_fail"
    redirect_to admin_products_path
  end

  def load_category
    @category = Category.find_by(id: params[:product][:category_id])
    return if @category

    flash[:error] = t "common.flash.load_category_fail"
    redirect_to new_admin_product
  end

  def load_childrens
    @categories = Category.childrens.select(:name, :id)
  end

  def product_params
    params
      .require(:product)
      .permit(:name, :quatity, :price, :image, :description)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product

  def edit
    store_location
  end

  private

  def load_product
    @product = Product.find_by(id: params[:id])
    return if @product

    flash[:error] = t "common.flash.load_product_fail"
    redirect_to root_path
  end
end

app/views/admin/products/_form.html.erb
<%= form_for @product, url: path do |f| %>
  <div class="row">
    <div class="col-md-12">
      <%= render "shared/error_message", object: f.object %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6 d-flex align-items-center">
      <%= f.label :name, class: "title-form" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <div class="form-group col-md-6 d-flex align-items-center">
      <%= f.label :quatity, class: "title-form" %>
      <%= f.number_field :quatity, class: "form-control" %>
    </div>
  </div>
  
  <div class="row">
    <div class="form-group col-md-6 d-flex align-items-center">
      <%= f.label :category_id, class: "title-form" %>
      <%= f.select :category_id, options_for_select(@categories.map { |c| [c.name, c.id]},@product[:category_id]),
        class: "form-control select-category" %>
    </div>
  
    <div class="form-group col-md-6 d-flex align-items-center">
      <%= f.label :price, class: "title-form" %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>
  
  <div class="row">
    <div class="form-group d-flex align-items-center col-md-6">
      <%= f.label :image, class: "title-form" %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    
    <div class="form-group d-flex align-items-center col-md-6">
      <%= f.label :description, class: "title-form" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit t("common.btn_submit"), class: "btn" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div style="margin-top: 80px">
    <%= render "form", path: admin_product_path %>
  </div>
</main>

app/views/admin/products/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="table-responsive">
  <%= link_to t(".btn_create"), new_admin_product_path, class: "btn btn-create" %>
    <table class="table table-striped table-sm table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th><%= t ".title_img" %></th>
          <th><%= t ".title_name" %></th>
          <th><%= t ".title_quatity" %></th>
          <th><%= t ".title_price" %></th>
          <th><%= t ".title_category" %></th>
          <th><%= t ".title_action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index  do |i, index| %>
          <tr id="table-item">
            <td><%= index + 1 %></td>
            <td><%= image_tag i.image , class: "img-product" if i.image.attached? %></td>
            <td><%= i[:name] %></td>
            <td><%= i[:quatity] %></td>
            <td><%= number_to_currency(i[:price]) %></td>
            <td><%= i.category[:name] %></td>
            <td>
              <%= link_to t(".btn_update"), edit_admin_product_path(i[:id]), class: "btn btn-update" %>
              <%= link_to t(".btn_delete"), admin_product_path(i[:id]), method: :delete, class: "btn btn-delete", data: {confirm: t("common.flash.confirm_delete")} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @products %>
  </div>
</main>

app/views/admin/products/new.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div style="margin-top: 80px">
    <%= render "form" %>
  </div>
</main>