config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :carts, only: [:create, :new, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :edit, :update]
  resources :products
  devise_for :users, path: "/" ,path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "sessions"}
  
  namespace :admin do
    resources :orders, only: [:index, :edit, :update]
    resources :products
    
    root "static_pages#dashboard"
  end

    # get "/login", to: "sessions#new"
    # post "/login", to: "sessions#create"
    # delete "/logout", to: "sessions#destroy"
end

app/views/layouts/_admin_side_bar.html.erb
<style>
@media (min-width: 768px){
  .nav, .nav .navbar {
    background-color: #f8f9fa !important;
  }
}
</style>

<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to "#", class: "navbar-brand col-md-3 col-lg-2 mr-0 px-3 px-2" do %>
    <%= image_tag "logo-white.png", alt:"Logo", id: "logo-admin" %>
  <% end %>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control m-0 form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to t("common.menu.logout"), destroy_user_session_path, class: "nav-link", method: :delete %>
    </li>
  </ul>
</nav>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="sidebar-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to admin_root_path , class: "nav-link #{controller?('admin/static_pages') ? 'active' : ''}" do %>
                <i class="fas fa-home icon-dash"></i>
                <%= t "common.menu.dashboard" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_orders_path , class: "nav-link #{controller?('admin/orders') ? 'active' : ''}" do %>
                <i class="far fa-file icon-dash"></i>
                <%= t "common.menu.order" %>
              <% end %>
              </li>
            <li class="nav-item">
              <%= link_to admin_products_path , class: "nav-link #{controller?('admin/products') ? 'active' : ''}" do %>
                <i class="fas fa-shopping-cart icon-dash"></i>
                <%= t "common.menu.product" %>
              <% end %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-user icon-dash"></i>
                <%= t "common.menu.customer" %>
              </a>
            </li>
          </ul>
        </div>
      </nav>

app/views/layouts/_footer.html.erb
<!-- Footer Start -->
<div class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="footer-widget">
          <h2><%= t "footer.get_in_touch" %></h2>
          <div class="contact-info">
            <p><i class="fa fa-map-marker"></i><%= t "footer.address" %></p>
            <p><i class="fa fa-envelope"></i>nhuthahuu@gmail.com</p>
            <p><i class="fa fa-phone"></i>0386741177</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="footer-widget">
          <h2><%= t "footer.follow_us" %></h2>
          <div class="contact-info">
            <div class="social">
              <%= link_to "#" do %> 
                <i class="fab fa-twitter"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fab fa-facebook-f"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fab fa-linkedin-in"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fab fa-instagram"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fab fa-youtube"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="footer-widget">
          <h2><%= t "footer.company" %></h2>
          <ul>
            <li><a href="#"><%= t "footer.about_us" %></a></li>
            <li><a href="#"><%= t "footer.privacy" %></a></li>
            <li><a href="#"><%= t "footer.term" %></a></li>
          </ul>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="footer-widget">
          <h2><%= t "footer.purchase_info" %></h2>
          <ul>
            <li><%= link_to t("footer.payment_policy") %></li>
            <li><%= link_to t("footer.shipping_policy") %></li>
            <li><%= link_to t("footer.return_policy") %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="row payment align-items-center">
      <div class="col-md-6">
        <div class="payment-method">
          <h2><%= t "footer.accept" %></h2>
          <%= image_tag "payment-method.png", alt:"Payment Method" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="payment-security">
          <h2><%= t "footer.secure" %></h2>
          <%= image_tag "godaddy.svg", alt:"Payment Security" %> <%= image_tag "norton.svg", alt:"Payment Security" %> <%= image_tag "ssl.svg", alt:"Payment Security" %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer End -->

app/views/layouts/_header.html.erb
<!-- Top bar Start -->
<div class="top-bar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <i class="fa fa-envelope"></i>
        nhuthahuu@gmail.com
      </div>
      <div class="col-sm-6">
        <div class="row justify-content-end">
          <div class="col-sm-3">
            <i class="fa fa-phone-alt"></i>
            0386741177
          </div>
          <div class="col-sm-3">
            <%= link_to "English", "?locale=en", class: "locale"%> | <%= link_to "Vietnamese", "?locale=vi", class: "locale"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Top bar End -->

<!-- Bottom Bar Start -->
<div class="bottom-bar">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-md-3">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag "logo.png", alt:"Logo" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="search">
          <%= text_field_tag "", "", placeholder: t("static_pages.home.title_search") %>
          <button><i class="fa fa-search"></i></button>
        </div>
      </div>
      <div class="col-md-3">
        <div class="user">
          <%= link_to "#", class: "btn wishlist" do %>
            <i class="fa fa-heart"></i>
            <span>(0)</span>
          <% end %>
          <%= link_to new_cart_path, class: "btn cart", id: "cart" do %>
            <i class="fa fa-shopping-cart"></i>
            <span id="cart_number" >(<%= current_cart_number %>)</span>
          <% end %>
          <% if loggin? %>
            <div class="btn btn-user">
              <i class="fas fa-user"></i>
              <span><%= current_user.fullname %></span>
              <ul class="user-login">
                <li> 
                  <%= link_to t("common.menu.profile"), "#" %>
                </li>
                <li>
                  <%= link_to t("common.menu.order"), orders_path %>
                </li>
                <li> 
                  <%= link_to t("common.menu.logout") ,destroy_user_session_path, method: :delete %> 
                </li>
              </ul>
            </div>
          <% else %>
            <%= link_to new_user_session_path, class: "btn btn-login" do %>
              <i class="fas fa-user"></i>
              <span><%= t "static_pages.home.login" %></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Bottom Bar End -->

app/views/layouts/_toast.html.erb
<div id="custom-toast"></div>
<% if flash[:success] %>
  <div id="content-toast-success" class="d-none"><%= flash[:success] %></div>
  <div id="title-toast-success" class="d-none"><%= t "common.flash.success" %></div>
<% elsif flash[:error] %>
  <div id="content-toast-fail" class="d-none"><%= flash[:error] %></div>
  <div id="title-toast-fail" class="d-none"><%= t "common.flash.error" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap"
        rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/toast" %>
    <%= render "layouts/header" unless is_admin? %>
    <%= render "layouts/admin_side_bar" if is_admin? %>
    <%= yield %>
    
    <% if is_admin? %>
        </div>
      </div>
    <% end %>
    
    <%= render "layouts/footer" unless is_admin? %>
  </body>
</html>